apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec: 
  selector:
    app: goserverapp #matchlabels do deployment
  type: LoadBalancer
  ports: 
  - name: gosesrver-service
    port: 8080
    targetPort: 80
    protocol: TCP
